### ISSUE TITLE
Thought about default way to define a page

### ISSUE THREAD

**Issue by arnaudmiribel** [blackary/mpa-config#3]
Wondering if it would not be cleaner to expect script_path in all situations instead of page_name when adding a new page. And if page_name is not given, then infer it from script_path (instead of the other way around). I find it "weird" that I have to title() manually my script path whenever I want to add it as a new page...

What do you think?

## Current behavior

By default, the user gives a page name, and the MPA will look for a script whose name equals `page_name.lower().replace(" ", "_")`

```
    pages:
      - page_name: Data Docs  # inferring script_path is pages/data_docs.py
        icon: 🗺
      - page_name: Data Sources
        icon: 📚
        script_path: pages/data_lookup.py
```

## Proposed behavior

If the user only gives a script path, then the MPA will infer the page name based on `script_path.replace("_", " ").title()`

```
    pages:
      - script_path: pages/data_docs.py  # inferring page_name is Data Docs
        icon: 🗺
      - script_path: pages/data_lookup.py
        icon: 📚
        page_name: Data Sources
```

---

**Yea a pretty strong cons to my proposed behavior is that it's great to lookup all pages by their titles. That's probably how you memorize them best.**
